# ??? DBMS ?? ?? ?? (chap01? persistence.xml? ?? ??)
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/menudb
    username: ohgiraffers
    password: ohgiraffers

# JPA ?? ?? ??
  jpa: # datasource? ?? ??
    show-sql: true # jpa? ????? ????? SQL? ??
    database: mysql # ??? ???? DBMS ??
    hibernate:
      ddl-auto: create # ddl : ??? ?? ??
      # - create : ?????? ?? ? ?? ???? ?? ?
      # ??? ??? Entity ??? ???? ???? ????.
      # - none : ?????? ??? ???? ??. ?? DB ??
      # - update : ?? ?????? ???? ???? ?? ????
      # ? ?? ?????? ???? ???? ?? ?? ?? ????
      # - create-drop : ???? ?????, ?? ??? drop ???.
    properties:  # hibernate? ?? ??
      hibernate:
        format_sql: true # sql? ???? ? ???? ?? ??